# conString='postgresql+psycopg2://[usuario]:[password]@[servidor]/baseDeDatos'
[connections.supabase]
SUPABASE_URL = "https://jqfydqljgazseemgsqjc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxZnlkcWxqZ2F6c2VlbWdzcWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTY4MjExNTQsImV4cCI6MjAzMjM5NzE1NH0.LgS3CxhPwpgVr0myWGamnlsCqvRf91F1Stw0zNcpwtg"